{"name": "test_create_task", "status": "broken", "statusDetails": {"message": "AttributeError: __enter__", "trace": "self = <api.test_tasks.TestTasks object at 0x0000022A2C70FBB0>\ncreate_and_delete_task = '86c3z4eba'\n\n    @allure.description(\"Создание задачи через API и проверяет, что она существует и отображается\")\n    def test_create_task(self, create_and_delete_task):\n        task_id= create_and_delete_task\n        api= TaskAPI()\n>       with allure,step(\"Получаем задачу по ID\"):\nE       AttributeError: __enter__\n\ntest_tasks.py:35: AttributeError"}, "description": "Создание задачи через API и проверяет, что она существует и отображается", "start": 1749657007381, "stop": 1749657007382, "uuid": "e4c2a563-96c7-40ee-a63e-c8ddc8ab82b3", "historyId": "8411cfe00c78d471e330400a032c1236", "testCaseId": "8411cfe00c78d471e330400a032c1236", "fullName": "tests.api.test_tasks.TestTasks#test_create_task", "labels": [{"name": "feature", "value": "Clickup API: Tasks"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "A1"}, {"name": "thread", "value": "49924-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}