{"name": "test_create_task_invalid_id", "status": "passed", "description": "Получение задачи по несуществующему ID", "steps": [{"name": "Пробуем получить задачу с фейковым ID", "status": "passed", "start": 1749923755075, "stop": 1749923756504}], "start": 1749923755075, "stop": 1749923756505, "uuid": "97badeb0-bd7b-4ad1-b1f9-0856ff79f2ae", "historyId": "d49665c155321fa39bc7114f9ad62555", "testCaseId": "d49665c155321fa39bc7114f9ad62555", "fullName": "tests.api.test_tasks.TestTasks#test_create_task_invalid_id", "labels": [{"name": "feature", "value": "Clickup API: Tasks"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "A1"}, {"name": "thread", "value": "13728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}