{"name": "test_create_task_invalid_id", "status": "passed", "description": "Получение задачи по несуществующему ID", "steps": [{"name": "Пробуем получить задачу с фейковым ID", "status": "passed", "start": 1749925212371, "stop": 1749925213804}], "start": 1749925212370, "stop": 1749925213805, "uuid": "2e546220-6bed-420b-a7b3-0fa512d4e107", "historyId": "d49665c155321fa39bc7114f9ad62555", "testCaseId": "d49665c155321fa39bc7114f9ad62555", "fullName": "tests.api.test_tasks.TestTasks#test_create_task_invalid_id", "labels": [{"name": "feature", "value": "Clickup API: Tasks"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "A1"}, {"name": "thread", "value": "37448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}