{"name": "test_create_task_without_name", "status": "broken", "statusDetails": {"message": "NameError: name 'LIST_ID' is not defined", "trace": "self = <api.test_tasks.TestTasks object at 0x000002126684B8B0>\ncreate_and_delete_task = '86c3z8q4w'\n\n    @allure.description(\"Проверка создания задачи без имени — должен вернуть ошибку\")\n    def test_create_task_without_name(self, create_and_delete_task):\n        with allure.step(\"Создаем задачу без имени\"):\n>           response= self.api.create_task(LIST_ID, name=\"\", status=\"to do\")\nE           NameError: name 'LIST_ID' is not defined\n\ntest_tasks.py:35: NameError"}, "description": "Проверка создания задачи без имени — должен вернуть ошибку", "steps": [{"name": "Создаем задачу без имени", "status": "broken", "statusDetails": {"message": "NameError: name 'LIST_ID' is not defined\n", "trace": "  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\tests\\api\\test_tasks.py\", line 35, in test_create_task_without_name\n    response= self.api.create_task(LIST_ID, name=\"\", status=\"to do\")\n"}, "start": 1749676279714, "stop": 1749676279714}], "start": 1749676279714, "stop": 1749676279715, "uuid": "7752d942-1578-4529-ba83-4bbace66cdbc", "historyId": "19c5729ffa9951a80e22d57809024d95", "testCaseId": "19c5729ffa9951a80e22d57809024d95", "fullName": "tests.api.test_tasks.TestTasks#test_create_task_without_name", "labels": [{"name": "feature", "value": "Clickup API: Tasks"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "A1"}, {"name": "thread", "value": "22800-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}