{"name": "test_success_login", "status": "failed", "statusDetails": {"message": "AssertionError: Page URL expected to be 'http://app.clickup.com/login'\nActual value: https://app.clickup.com/login \nCall log:\n  - PageAssertions.to_have_url with timeout 5000ms\n  - waiting for locator(\":root\")\n    8 × locator resolved to <html dir=\"ltr\" lang=\"en-US\">…</html>\n      - unexpected value \"https://app.clickup.com/login\"", "trace": "page = <Page url='https://app.clickup.com/login'>\n\n    @allure.feature(\"UI: Авторизация ClickUp\")\n    @allure.description(\"Проверяем, что пользователь может войти через форму логина\")\n    def test_success_login(page):  #фикстура\n        login_page=LoginPage(page) #экземпляр\n>       login_page.login()         #вызов метода\n\ntest_login_page.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\pages\\login_page.py:19: in login\n    self.open()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.login_page.LoginPage object at 0x00000264AAA706D0>\n\n    @allure.step(\"Переход по адресу BASE_URL + endpoint\")\n    def open(self):\n        \"\"\"Переход на полный URL: BASE + endpoint\"\"\"\n        full_url =self._get_full_url()\n        self.page.goto(full_url)\n        self.page.wait_for_load_state(\"load\")\n>       expect(self.page).to_have_url(full_url)\nE       AssertionError: Page URL expected to be 'http://app.clickup.com/login'\nE       Actual value: https://app.clickup.com/login \nE       Call log:\nE         - PageAssertions.to_have_url with timeout 5000ms\nE         - waiting for locator(\":root\")\nE           8 × locator resolved to <html dir=\"ltr\" lang=\"en-US\">…</html>\nE             - unexpected value \"https://app.clickup.com/login\"\n\n..\\..\\pages\\base_page.py:23: AssertionError"}, "description": "Проверяем, что пользователь может войти через форму логина", "steps": [{"name": "Логинимся в ClickUp через UI", "status": "failed", "statusDetails": {"message": "AssertionError: Page URL expected to be 'http://app.clickup.com/login'\nActual value: https://app.clickup.com/login \nCall log:\n  - PageAssertions.to_have_url with timeout 5000ms\n  - waiting for locator(\":root\")\n    8 × locator resolved to <html dir=\"ltr\" lang=\"en-US\">…</html>\n      - unexpected value \"https://app.clickup.com/login\"\n\n", "trace": "  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\pages\\login_page.py\", line 19, in login\n    self.open()\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\pages\\base_page.py\", line 23, in open\n    expect(self.page).to_have_url(full_url)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 19027, in to_have_url\n    self._sync(\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 127, in to_have_url\n    await self._expect_impl(\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 74, in _expect_impl\n    raise AssertionError(\n"}, "steps": [{"name": "Переход по адресу BASE_URL + endpoint", "status": "failed", "statusDetails": {"message": "AssertionError: Page URL expected to be 'http://app.clickup.com/login'\nActual value: https://app.clickup.com/login \nCall log:\n  - PageAssertions.to_have_url with timeout 5000ms\n  - waiting for locator(\":root\")\n    8 × locator resolved to <html dir=\"ltr\" lang=\"en-US\">…</html>\n      - unexpected value \"https://app.clickup.com/login\"\n\n", "trace": "  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\pages\\base_page.py\", line 23, in open\n    expect(self.page).to_have_url(full_url)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 19027, in to_have_url\n    self._sync(\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 127, in to_have_url\n    await self._expect_impl(\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 74, in _expect_impl\n    raise AssertionError(\n"}, "steps": [{"name": "Формируем полный URL из BASE и endpoint", "status": "passed", "start": 1749769818249, "stop": 1749769818249}], "start": 1749769818249, "stop": 1749769831379}], "start": 1749769818249, "stop": 1749769831381}], "start": 1749769818249, "stop": 1749769831382, "uuid": "ba98ceea-be8d-465e-b699-0f50e14d6bb0", "historyId": "c6a22e536473bfc0007634209572dfe6", "testCaseId": "c6a22e536473bfc0007634209572dfe6", "fullName": "tests.ui.test_login_page#test_success_login", "labels": [{"name": "feature", "value": "UI: Авторизация ClickUp"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_login_page"}, {"name": "host", "value": "A1"}, {"name": "thread", "value": "34664-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_login_page"}]}